### ISSUE TITLE
r6052 - не собираются плагины

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#1]
Проблема сборки в r6052 связанная с разрывом синхронизации в SVN в r6050 - http://wj32.org/processhacker/forums/viewtopic.php?f=24&p=6007#p6007 и если взять те же плагины от r6047, то WaitChainPlugin сообщает о не найденной процедуре и не работает - PH его отключает. :(

**Comment by dmex** [comment]
Fixed :+1:

**Comment by VictorVG** [comment]
Big thanks!
