### ISSUE TITLE
Build error on WaitChainPlugin patch for rename HashtableCompareFunction -> HashtableEqualFunction

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#10]
Just patch, is very simply, please:

```
wndtree.c
--- wndtree.c   Fri Jan 15 12:35:04 2016
+++ wndtree.c
@@ -23,7 +23,7 @@
 #include "wndexp.h"
 #include "resource.h"

-BOOLEAN WepWindowNodeHashtableCompareFunction(
+BOOLEAN WepWindowNodeHashtableEqualFunction(
     _In_ PVOID Entry1,
     _In_ PVOID Entry2
     );
@@ -57,7 +57,7 @@

     Context->NodeHashtable = PhCreateHashtable(
         sizeof(PWE_WINDOW_NODE),
-        WepWindowNodeHashtableCompareFunction,
+        WepWindowNodeHashtableEqualFunction,
         WepWindowNodeHashtableHashFunction,
         100
         );
@@ -103,7 +103,7 @@
     PhDereferenceObject(Context->NodeRootList);
 }

-BOOLEAN WepWindowNodeHashtableCompareFunction(
+BOOLEAN WepWindowNodeHashtableEqualFunction(
     _In_ PVOID Entry1,
     _In_ PVOID Entry2
     )

```

Patch resolved error and warning:

> Ошибка          C2065   PPH_HASHTABLE_COMPARE_FUNCTION: необъявленный идентификатор                                          .\plugins-extra\WaitChainPlugin\wndtree.c::59
> Предупреждение  C4047   функция: "PPH_HASHTABLE_EQUAL_FUNCTION" отличается по уровням косвенного обращения от "int"          .\plugins-extra\WaitChainPlugin\wndtree.c::59
> Предупреждение  C4024   PhCreateHashtable: различные типы для формального и фактического параметров 2                        .\plugins-extra\WaitChainPlugin\wndtree.c::59
> Ошибка          C2146   синтаксическая ошибка: отсутствие ")" перед идентификатором "WepWindowNodeHashtableCompareFunction"  .\plugins-extra\WaitChainPlugin\wndtree.c::59
> Ошибка          C2198   PhCreateHashtable: слишком мало аргументов для вызова                                                .\plugins-extra\WaitChainPlugin\wndtree.c::59

**Comment by wj32** [comment]
Fixed in b330496cb782a815bc3d8e213ea3fd7a353f12a2.
