### ISSUE TITLE
How do I install plugins to ProcessHacker?

### ISSUE THREAD

**Issue by SalmonSnakeD** [processhacker/plugins-extra#100]
I have no idea how to install these plugins to Process hacker, do I need any external software to do it? Could someone tell me how to install plugins to Process Hacker, I am not a coding expert.

**Comment by dmex** [comment]
The plugins folder?

**Comment by TuTAH1** [comment]
Better question is where can I download **compilted** ProcessHacker plugins?

**Comment by dmex** [comment]
There are none. Process Hacker was renamed System Informer and functionality was merged into the application.
