### ISSUE TITLE
Build some plugins-extra problem befor "Add normal and logarithmic scale grids" PH commit 6e4b7498facff87

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#11]
Compiler log (partial):

> 8>------ PerfMonPlugin, Release Win32 ------
> 7>  main.c
> 7>  wndtree.c
> 8>  graph.c
> 8>  main.c
> 8>  options.c
> 8>graph.c(149): error C2065: PH_GRAPH_USE_GRID: not defined
> 8>graph.c(311): error C2065: PH_GRAPH_USE_GRID: not defined
> 9>------ NvGpuPlugin, Release Win32 ------
> 9>  details.c
> 9>  graph.c
> 9>  main.c
> 9>  nvidia.c
> 9>  options.c
> 9>graph.c(291): error C2065: PH_GRAPH_USE_GRID: not defined
> 9>graph.c(357): error C2065: PH_GRAPH_USE_GRID: not defined
> 9>graph.c(442): error C2065: PH_GRAPH_USE_GRID: not defined
> 9>graph.c(509): error C2065: PH_GRAPH_USE_GRID: not defined
> 9>graph.c(812): error C2065: PH_GRAPH_USE_GRID: not defined
> 11>------ DiskDrivesPlugin, Release Win32 ------
> 10>  filter.c
> 10>  log.c
> 10>  main.c
> 10>  dialog.c
> 10>  message.c
> 11>  disks.c
> 11>  graph.c
> 11>  main.c
> 11>  options.c
> 11>graph.c(193): error C2065: PH_GRAPH_USE_GRID: not defined
> 11>graph.c(412): error C2065: PH_GRAPH_USE_GRID: not defined
> ========== Build: success: 14, error: 3, no changed: 0, skip: 0 ==========

x86-64 is not build - there is certainly the same errors are displayed. Looked itself changes, but not sure that I understood correctly - I can do just to replace _PH_GRAPH_USE_GRID_  up to _PH_GRAPH_USE_GRID_X | PH_GRAPH_USE_GRID_Y | PH_GRAPH_LOGARITHMIC_GRID_Y_ ?

**Comment by wj32** [comment]
Fixed in 301602910c6c046c17b82427d2c82e560d4c4e3f.

**Comment by VictorVG** [comment]
Thanks! I test my fix and see:

![ph_r20337](https://cloud.githubusercontent.com/assets/906886/12850881/1f7a9e40-cc38-11e5-9e2b-61a3b8307677.png)
