### ISSUE TITLE
FirewallMonitorPlugin hardcoded include path

### ISSUE THREAD

**Issue by TETYYS** [processhacker/plugins-extra#13]
fwtab.c @ 25:

```
#include "..\..\plugins\include\toolstatusintf.h"
```

File exists in `processhacker2\plugins\include\toolstatusintf.h`, but when building in completely seperate folder with SDK inc and lib specified in completely seperate folder, build fails.

**Comment by dmex** [comment]
This header is not part of the SDK... It requires a direct path from the plugins folder and there's not much that can be done about that.
