### ISSUE TITLE
Compiled DLLs

### ISSUE THREAD

**Issue by stdedos** [processhacker/plugins-extra#14]
_This is not a real issue, I am sorry that I use that communication way_

On the forums you inform that compiled versions can be provided.
If they are indeed stable, could they be pushed as well, or even, considered a release?

**Comment by dmex** [comment]
What plugin did you need?

**Comment by stdedos** [comment]
I'd be interested in DbgView (since the new version disables it) and FirewallMonitor.
A small file that gives one-line explaination could be usefull

**Comment by dmex** [comment]
You don't need them anymore?

**Comment by stdedos** [comment]
Oh, I do want them. I mistakenly pressed close!

**Comment by dmex** [comment]
They're still too unstable to make available for download :|

If you leave the ticket open then I'll let you know when they can finally be downloaded (which will be whenever I have the time to debug multiple issues).

**Comment by dmex** [comment]
I've started providing some compiled versions on the Releases page:
https://github.com/processhacker2/plugins-extra/releases

It doesn't yet include DbgView and FirewallMonitor but they should be available very soon... I'll leave the ticket open until they're available.

**Comment by cpriest** [comment]
Any word on these extras?  I'm a huge fan of ProcessHacker

**Comment by dmex** [comment]
@cpriest 

I keep getting bug reports from users that they're unstable or have memory leaks and I don't have the time to work out whats wrong :/

**Comment by stdedos** [comment]
@dmex Well, would it be possible that Pre-Releases are still coming?
![image](https://user-images.githubusercontent.com/133706/33794913-c48423fe-dcdd-11e7-96ba-ad4484c699a0.png)

At least, you will have a full rundown on the issues for "when you have time" 😄

**Comment by sgeto** [comment]
> I keep getting bug reports from users that they're unstable or have memory leaks and I don't have the time to work out whats wrong :/

I am using them for a few months now. Didn't try all of them that much but as I far as I can tell they are _mostly_ stable. Except for the `FirewallMonitor`. That thing is a mess. I actually made a stackwalk of it and I wanted to send that in, but it got deleted...
I'll go for another one.

@stdedos
If you need Pre-Releases, and don't have the ability or time to build them yourself, you could use appveyor:

[Debug64 ](https://ci.appveyor.com/api/buildjobs/7tw1j9hd2oxboocl/artifacts/bin%2FDebug64%2Fplugins.7z)
[Debug32 ](https://ci.appveyor.com/api/buildjobs/7tw1j9hd2oxboocl/artifacts/bin%2FDebug32%2Fplugins.7z)

extract these and place **the once you need** in the plugin folder. Stay away from `FirewallMonitor `though! You've been warned :smile

**Comment by cpriest** [comment]
I see, I thought they had maintainers.

**Comment by stdedos** [comment]
Well, they do (I could list them, but I don't wanna spam them :D)

It's just on their free time only

**Comment by cpriest** [comment]
I get it, I have a few OS projects as well that I have little time 
for.   No worries.

I wish someone would write some OS software that gave us more free time, 
heh.

**Comment by dmex** [comment]
The plugins here are incomplete and shouldn't be used unless you're able to compile the code.
