### ISSUE TITLE
Information: Filrewall Monitor posibly memory leak on Windows 10 - ru-borad users report.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#17]
Users report's:

Russian (original)

1) [**1-th report**](http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3200#18)

> **towarish**
> 
> Господа потребление памяти у Process Hacker v3.0.0.79   600-800 мегабайт , это нормально?
> У меня win 10 x64. 

2) [**2-th report**](http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3220#3)

> > **ewild**
> > 
> > Или у вас включён плагин FireWall Monitor. Говорят иногда стоит и документацию читать, хотя это и не обязательно. :smile:
> 
> Ха, только что глянул у себя: Process Hacker @ Win10 x64 1511 - Private Bytes 1.25GB.
> После отключения плагина FireWall Monitor - пока 16-17MB. 

English (partial translation)

1)

> **tovarish**
> 
> Lord memory consumption in Process Hacker v3.0.0.79 600-800 megabytes, is this normal?
> I win 10 x64.
> 2)
> **ewild**
> 
> > Or do you have enabled the plugin FireWall Monitor. It is sometimes worth to read the documentation, though this is not required. :smile:
> 
> Ha, just looked at: Process Hacker @ Win10 x64 1511 - Private Bytes 1.25GB. 
> After switching off FireWall Monitor plugin - is 16-17MB.

It looks like some people just read the documentation when everything crashed. :smile:

**Comment by dmex** [comment]
Why are you even distributing the plugins from plugins-extra?

Every single last one is unstable, unfinished and not available for download because they have serious issues.

**Comment by dmex** [comment]
Plugin has been deleted.

**Comment by VictorVG** [comment]
Ok!

**Comment by VictorVG** [comment]
I do not know, but I think not wanting to read the documentation that after screaming about problems is the apparent lack of brains. Already psle how many times we said "Read the documentation!" the same people her and do not read, but the cry that they have problems ...
