### ISSUE TITLE
NvGpuPlugin - AV on startng in Win10 after commit f5d4754 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#18]
Win10 PH v3.0.0.139 is crash then Access Violation on module NvGpuPlugin v1.1.0.0 
Git f5d47540f3a15050f2e2b767855ce58171a14dc5. On Win7 plug-in working is success...

**Comment by VictorVG** [comment]
Temporary: I modfy my installation script section _Files_

```
Source: "..\..\bin\Release32\plugins\NvGpuPlugin.dll"; DestDir: "{app}\plugins"; Flags: ignoreversion; OnlyBelowVersion: 0,6.2; Components: plugins\nvgpu; Check: not Is64BitInstallMode()
Source: "..\..\bin\Release64\plugins\NvGpuPlugin.dll"; DestDir: "{app}\plugins"; Flags: ignoreversion; OnlyBelowVersion: 0,6.2; Components: plugins\nvgpu; Check: Is64BitInstallMode()
```

before resolving this issues.

**Comment by VictorVG** [comment]
Added new information (_19.06.2016, 09:50 msk_):

> **KLASS**
> 
> In order to check NvGpuPlugin plugin translation, I stumbled upon ... Win8.1, just a card from Nvidia. Translation checked-be was at 8.1 subject to NvGpuPlugin runs and work.
> 
> ![561be567a6b644101ce21b268187918b](https://cloud.githubusercontent.com/assets/906886/16175909/2c94748c-3607-11e6-9920-95d3309db228.png)

**Comment by VictorVG** [comment]
Added info, by **KLASS** - only Windows 10 NvGpuPlugin.dll generated AV:

![1](https://cloud.githubusercontent.com/assets/906886/16177421/63e3e12e-3635-11e6-9e9b-cf1433c979f3.png)

**Comment by VictorVG** [comment]
Problem source is found - needed driver and active NVIDIA card. Workraund - on PH System Information window open and startup check 

_If Current.Active GPU NVIDIA and Driver NVIDIA r340 or higest Then Load NvGpuPlugin.dll Else Skip load NvGpuPlugin.dll or If Open SIWindow then Unload NvGpuPluagin.dll EndIf EndIf_

Samples ...

**Comment by VictorVG** [comment]
The assumption was confirmed - update driver NVIDIA R368.39 to R368.69. The upgrade process removes the driver from the operating system restarting in VGA mode on some computers. In this case, there is a plugin AV, to v3.0.0.138 exclusively in such situations did not arise AV. All systems used NVIDIA GTX 550 Ti (GF116), GTX 650 (GK107) and Quadro K6000 (GK110GL) videocard.

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
@dmex 

Big thanks! :+1:
