### ISSUE TITLE
When you run the Terminator does not check that KProcessHacker 2 driver is already installed

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#19]
When you run the Terminator does not check that KProcessHacker 2 driver is already installed.

When you run the Terminator does not verify that the driver is already installed KProcessHacker 2 that leads to excess error message _Unable to install KProcessHacker2_ in ./TerminatorPlugin/dialog.c the next plug-in startup.

I can see a way to eliminate this phenomenon:

`If (scm SERVICE_KERNEL_DRIVER exists) Then skip_install Else install_driver Endif;`

**Comment by TETYYS** [comment]
KPH_DEVICE_SHORT_NAME should be KProcessHacker3 instead of 2

**Comment by VictorVG** [comment]
Thanks!
