### ISSUE TITLE
[Request] Terminator Plugin - Deselect All Option and its appropriate complement

### ISSUE THREAD

**Issue by CeruleanSky** [processhacker/plugins-extra#20]
As long as the terminator plugin is being rewritten, a deselect all checkboxes option is a small request to add.

 Or perhaps a smaller default selection so the safer termination options would be tried first.  And for people who want the process and perhaps their computer to combust, a select everything option or its more timid option to populate the checkboxes with the choices currently selected by default in process hacker 2.96.

**Comment by dmex** [comment]
closing since terminator is deprecated
