### ISSUE TITLE
FirewallMonitorPlugin - memory leak in Win10/Server 2012 R2

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#21]
ru-board user **AKRAV** sent test report in to topic [**PROGRAMS :: Process Hacker**](http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3680#3)

> **VictorVG4**
> 
> whether a memory leak seen in the latest build 3.0.159?
> 
> I ate about 2 gigs, with tried before a localized version of Process Hacker KLASS and noticing this, I thought maybe the location. Then restart your assembly (in the form of a portable file that) processhacker-3.0-bin.zip and here for the night again about 2.01 Giga.
> All plug-ins are enabled by default, all that is in the archive.
> Always use version x64.
> 
> Maybe it was in previous builds., Just do not pay attention, and do not always use (running) program.
> 
> PS: Windows in October 1607 Build 14393 x64

**Summary:**

![3a9fe9561fca8ce589b082829c9277c8](https://cloud.githubusercontent.com/assets/906886/18774053/e7ebab28-815d-11e6-8b90-8998115a2b06.png)

According to observations **AKRAV** user if you enable this plug-in some configurations of Windows 10 / Server 2012 R2 memory leak occurs. The search for the causes of the phenomenon showed the presence of a memory leak in the plugin FirewallMonitor.

**Comment by VictorVG** [comment]
In my install script I partially revert changes installer script build 27 - added check `OnlyBelowVersion: 0,6.3` for FirewallMonitor then plugin have memory leak in Win10. But in Win 7 - 8.1 FirewallMonitorPlugin not have this problem and I temporary set restrictions for OS version for install this plugin as Windows 8.1.

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Big thanks!
