### ISSUE TITLE
Wish: Saving column set and size is wihs's features for FirewallMonitor 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#22]
**Wish:**

On current realization is FirewallMonitor not reminder user column choice and size and then Process
Hacker reboot always reset this parameters on to default.

Step for test:

1) Choice any column set and size in to Firewall tab;
2) Exit Process Hacker;
3) Start Process Hacker new
4) Open Firewall tab
5) See - column set and all column  size reset by defaul.

Tested on Windows 7 SP1 and Windows 10 ( report by **KLASS** on http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3780#19).

Screenshot's:

_Screenshot before step 1)_

![1](https://cloud.githubusercontent.com/assets/906886/19930003/4899535c-a117-11e6-838d-a98050a5b9e2.png)

_Screenshot after step 1)_

![2](https://cloud.githubusercontent.com/assets/906886/19930090/d9001a20-a117-11e6-87e5-b687fe9d97ed.png)

_Screenshot step 5)_

![3](https://cloud.githubusercontent.com/assets/906886/19930209/69e28622-a118-11e6-87ad-29578ddafbc9.png)

**Comment by dmex** [comment]
Done

**Comment by VictorVG** [comment]
Big thanks!
