### ISSUE TITLE
Question: warning LNK4199 on build ExtraPlugins\ExtraPlugins.vcxproj at windowscodecs.dll

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#24]
I have warning LNK4199 (function not used) in build ExtraPlugins\ExtraPlugins.vcxproj. Script out (sorry,  encoded mismatch :( ):

![1](https://cloud.githubusercontent.com/assets/906886/20244663/8d6aef04-a99b-11e6-81e0-b131335e3d1b.png)

grep output:

> [1] ExtraPlugins\ExtraPlugins.vcxproj
>       <DelayLoadDLLs>windowscodecs.dll;bcrypt.dll;winhttp.dll;uxtheme.dll;%(DelayLoadDLLs)</DelayLoadDLLs>
>       <DelayLoadDLLs>windowscodecs.dll;bcrypt.dll;winhttp.dll;uxtheme.dll;%(DelayLoadDLLs)</DelayLoadDLLs>
>       <DelayLoadDLLs>windowscodecs.dll;bcrypt.dll;winhttp.dll;uxtheme.dll;%(DelayLoadDLLs)</DelayLoadDLLs>
>       <DelayLoadDLLs>windowscodecs.dll;bcrypt.dll;winhttp.dll;uxtheme.dll;%(DelayLoadDLLs)</DelayLoadDLLs>
> 
> [2] ExtraPlugins\obj\Release32\ExtraPlugins.tlog\link.command.1.tlog
> /OUT:".\TRUNK\PLUGINS-EXTRA\..\BIN\RELEASE32\PLUGINS\EXTRAPLUGINS.DLL" /INCREMENTAL:NO /NOLOGO /LIBPATH:../../SDK/LIB/I386 WINDOWSCODECS.LIB BCRYPT.LIB WINHTTP.LIB UXTHEME.LIB PROCESSHACKER.LIB NTDLL.LIB KERNEL32.LIB USER32.LIB GDI32.LIB WINSPOOL.LIB COMDLG32.LIB ADVAPI32.LIB SHELL32.LIB OLE32.LIB OLEAUT32.LIB UUID.LIB ODBC32.LIB ODBCCP32.LIB DELAYIMP.LIB /DELAYLOAD:WINDOWSCODECS.DLL /DELAYLOAD:BCRYPT.DLL /DELAYLOAD:WINHTTP.DLL /DELAYLOAD:UXTHEME.DLL /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:".\TRUNK\PLUGINS-EXTRA\..\BIN\RELEASE32\PLUGINS\EXTRAPLUGINS.PDB" /SUBSYSTEM:WINDOWS,"6.01" /OPT:REF /OPT:ICF /LTCG /TLBID:1 /RELEASE /DYNAMICBASE /NXCOMPAT /IMPLIB:".\TRUNK\PLUGINS-EXTRA\..\BIN\RELEASE32\PLUGINS\EXTRAPLUGINS.LIB" /MACHINE:X86 /SAFESEH /DLL ".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\EXTRAPLUGINS.RES"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\CLOUD.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\DIALOG.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\DISABLED.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\ARRAYLIST.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\DEBUG.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\JSON_C_VERSION.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\JSON_OBJECT.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\JSON_OBJECT_ITERATOR.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\JSON_TOKENER.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\JSON_UTIL.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\LIBJSON.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\LINKHASH.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PRINTBUF.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\RANDOM_SEED.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\MAIN.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\MINIZ.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PLUGIN.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\SEARCHBOX.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PAGE4.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PAGE1.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PAGE2.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PAGE3.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\PAGE5.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\UPDATER.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\VERIFY.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\UNINSTALL.OBJ"".\TRUNK\PLUGINS-EXTRA\EXTRAPLUGINS\OBJ\RELEASE32\WNDTREE.OBJ"

Like all works, but it confuses me a warning. How better to do? Ignore the warning or temporarily comment out the call line windowscodecs.dll in the project? I beg your tips.

**Comment by dmex** [comment]
makesdk.cmd or makesdk_rebuild.cmd?

**Comment by VictorVG** [comment]
Big thanks!
