### ISSUE TITLE
NetExtrasPlugin - Missing from source solution file?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [processhacker/plugins-extra#25]
Hi there,

I really like the work you and the community has been doing just having discovered process hacker myself, however there are 21 plugin folders but only 20 are in the solution file, NetExtrasPlugin is missing, it is a visible option under the plugin manager "Browse" as "Network Extras" (to download, which fails) confirming it wasn't built.

I am using the latest from this repository along with your latest nightly build, but the same is true if I build PH2 from the latest available source as well, although I noticed the plugin interface is different.

Thanks, appreciate your assistance. 🎱 :)

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I see https://github.com/processhacker2/plugins-extra/commit/3186bb8e9fb8bf867b5e45e4d9c67e3b47f7b2ee committed an hour ago, so I will close this ticket since this plugin was merged with "NetworkTools". 

Thanks.

**Comment by dmex** [comment]
@L-a-n-g-o-l-i-e-r-s 

Yeah, the functionality of NetExtrasPlugin was merged into the nightly builds of Process Hacker 👍
