### ISSUE TITLE
Terminator and Valve Anti-Cheat

### ISSUE THREAD

**Issue by unforgettableid** [processhacker/plugins-extra#28]
Hi!

Maybe it would be good if Terminator would warn users before terminating a process protected by Valve Anti-Cheat (VAC)?

Would this be feasible and easy to implement, at least for the most common VAC-protected processes?

I don't use Steam, but this feature might be useful for others.

**Comment by unforgettableid** [comment]
Related:  https://github.com/processhacker2/plugins-extra/issues/26

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
How do we know it's specific to terminating VAC guarded processes and not just even being loaded with PH2?

**Comment by unforgettableid** [comment]
Oh. :( You're right. Maybe if Terminator is loaded at all, Valve will instantly ban the user for life. Maybe not. I dunno.

Could some non-gamer Process Hacker user create a throwaway Steam account and run an experiment?

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
If you decide to try to test that, don't associate the same phone number with your main, it will VAC ban accounts linked to the same phone or other details.

**Comment by dmex** [comment]
There's already a warning when opening the terminator window.
