### ISSUE TITLE
FirewallMonitor functional?

### ISSUE THREAD

**Issue by Volkanite** [processhacker/plugins-extra#3]
Is the FirewallMonitor plugin functional as yet? I get an error loading on r6153: "The specified procedure could not be found". I would have posted this issue on the Forums/plugins-extra thread but i didn't see this plugin listed for download yet which means it might be a new plugin still in testing. I'm on Win7 x64 SP1 (BuildLabEx: 7601.17514.amd64fre.win7sp1_rtm.101119-1850). Is it even for win7?

![2015-06-28 17_59_50-process hacker](https://cloud.githubusercontent.com/assets/9159000/8398520/bd48339e-1dbf-11e5-8b37-f264a15c7dcb.jpg)

**Comment by VictorVG** [comment]
Linker naughty inserting an incorrect challenge - a challenge to monitor.c FwpmNetEventSubscribe, but linker delivers FwpmNetEventSubscribe1() where it is necessary to substitute FwpmNetEventSubscribe0() (possible Microsoft seems once again to make mistakes and do not hurry to change them :))  - this plug-in is import FwpmNetEventSubscribe1() specified for Windows 8 (https://msdn.microsoft.com/en-us/library/windows/desktop/hh969199%28v=vs.85%29.aspx), but for Windows 7 exists FwpmNetEventSubscribe0() (https://msdn.microsoft.com/en-us/library/windows/desktop/dd744937%28v=vs.85%29.aspx). This function can't compatible on Windows XP/Vista/Server 2003.

**Comment by VictorVG** [comment]
There's a second thing and get out if hex-editor to correct the name of the import - by an administrator with UAC disabled on Win7 tab appears, but the message is displayed insufficient privilege account, and this is possible only when UAC is enabled.

**Comment by VictorVG** [comment]
I build commit c0bbc3f96a4d104f50e3b4782e42f819ea9bd68b but both of these problems is present:

1) linker inserts code output API call for Win8 and try switching tools assembly failed:

imports **fwpuclnt.dll**:

FwpmEngineClose0
FwpmEngineOpen0
FwpmEngineSetOption0
FwpmFilterGetById0
FwpmFreeMemory0
FwpmLayerGetById0
**FwpmNetEventSubscribe1** _<--- Win8 API linker ignoririruet specify ld :: System == 5.01_
FwpmNetEventUnsubscribe0

2) even if the correct name manually import all one require administrator rights while ignoring their presence:

![fwmon](https://cloud.githubusercontent.com/assets/906886/8406494/896c3ae2-1e65-11e5-9ba2-be580a871b34.png)

**Comment by VictorVG** [comment]
Problem is presence, because voiced his hypothesis in a forum PM. :(

**Comment by dmex** [comment]
This plugin was originally created in 2012 but dropped due to issues with Windows 7 support.

It's back from the dead and for now will have some issues while it's updated to the latest sdk... This plugin doesn't show much information on Windows 7 because you only see Dropped events... Windows 8 and Windows 10 show both Dropped and Allowed plus substantially more information about the individual events.

Please confirm its actually working (e.g. Shows dropped events on Win7) for me to close this ticket :+1:

**Comment by VictorVG** [comment]
Build, check - test is success:

![test](https://cloud.githubusercontent.com/assets/906886/8432423/a327c436-1f48-11e5-8239-ec4c7ebceb87.png)

OS Win7 SP1 x64, using internal IPFilter

**Comment by Volkanite** [comment]
Works! can close.
