### ISSUE TITLE
Git-b1c01f3a14d9 : Terminator - unnecessary error messages when the plugin is called. 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#31]
When you call the plug-in, the OS displays two extra error messages:

in startup:

![459257eff086](https://cloud.githubusercontent.com/assets/906886/25062730/6cf1eaf4-21da-11e7-9581-12950fccf677.jpg)

then:

![9ef0f536edf9](https://cloud.githubusercontent.com/assets/906886/25062729/6cebae3c-21da-11e7-9f12-763bafbd0f8d.jpg)

but plug-in is work success.

**Comment by dmex** [comment]
I don't know what that error message says?

**Comment by skipik** [comment]
@dmex The first one says "Couldn't install KProcessHacker2. Inadmissible object name". The second one "Couldn't connect to KProcessHacker2. Object with such name wasn't found".

**Comment by VictorVG** [comment]
@**dmex**

Forgive ... In a hurry, I did not pay attention to the language of error messages and copied the originals instead of the translation into the report.

@**skipik** 

Thank for translation!
