### ISSUE TITLE
Firewall Monitor plugin can't show WFP events in to Win7 SP1 in to v3.0.5234.707

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#34]
In to Win7 SP1 Firewall Monitor plugin can't show WFP events - I see only blank Firewall tabs:

![1](https://user-images.githubusercontent.com/906886/26961071-b8432e2a-4ce4-11e7-92db-1a16accc4d4a.png)

other plugins is work success.

**Comment by VictorVG** [comment]
Notes - this Issues for memory for task is exists.

**Comment by dmex** [comment]
This issue was fixed some time ago.
