### ISSUE TITLE
FIXED: DNSCashe plugin is crach on win10x32 1511, PH 3.0.924 then press Flush button

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#42]
On [**forum.ru-board.com**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=1060#9) user report (sorry, but information is minimum :( )  :

> **spurionzx**
> when you click reset the DNS cache, win10x32 1511, PH 3.0.924
> 
> ![1](https://user-images.githubusercontent.com/906886/29673222-3b5ef64c-88f7-11e7-8034-c807e871a47b.jpg)

Judging by the dating of the bug-report it is a question of Git-bf93830, at the moment the user is provided for testing Git-81755ba and I'm waiting for his report on the error correction check.

When tested on independent machines running Win 7 SP1 x64 and Win 10 1607 x64, this error was not reproduced in to Process Hacker v3.0.05451.924 on Nightly, my personal or Russian translated my personal build by **KLASS**.

**Comment by VictorVG** [comment]
On user report - problem is resolved in to Git 81755ba . I make status this issues as _FIXED_ and close it. Big thanks!

**Comment by dmex** [comment]
@univert 

Just checking if your PR fixed this issue?

**Comment by univert** [comment]
I do not have 32bit system. So I did no encounter this problem previously.  In #41 there is a lot of refactor, this issue may be fixed by the refactor though.

**Comment by VictorVG** [comment]
At us with **KASS** also have only х64 systems where described **spurionzx** the phenomenon was not reproduced, but according to him the last commit it is corrected.

With the fact that during the refactoring, the previously introduced error can be eliminated and I met in Far Manager, although there are times when the word "refactoring" in the change log is instantly alarming :) - especially if dozens of source files are exposed at once to the refactoring - here almost always in changelog We see records like:

> Drkns 05/05/2017 00:31:34 +0000 - build 4953
> 
> 1. Correction of 4952.
> 
> Drkns 04/05/2017 20:45:42 +0000 - build 4952
> 
> 1. Refactoring.

Or instead of Correction there can be a record Fix b ..., Fix typo b ... - since. The refactoring robot breaks something, and a person in a large volume of changes can not always see it.
