### ISSUE TITLE
MemoryExtPlugin don't compile x86 build

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#44]
MemoryExtPlugin don't compile x86 build

MemoryExtPlugin, Win32 

pfn.c :: string 1067 :: error C2220 --- ???? possible /WX flag?
pfn.c :: string 1067 :: warning C4244: function: convert "ULONGLONG" to "ULONG_PTR", possible data lost

_Also question - if I call this plug-in on Win 7 SP1 x64 I have system error messages about incorrect function parameter. Passible this plug-in writhed for Win8.1 or letter?_

![1](https://user-images.githubusercontent.com/906886/31159474-08dfe064-a8d2-11e7-9770-0c28c0558c33.png)

**Comment by VictorVG** [comment]
**Build fixed** - x86 release compiled is success, but my question is exist - error messages "_Unable to query the PFN data base: service or function call use incorrect parameter as arg2_". OS Win7 SP1 x64. 

What should I do with this error message? While I add to the script a check for the OS version is not lower than Win81, but on MSDN the answer to the question "Were there such changes in the API between Win7 and Win81 that made them incompatible?" I have not yet found.

**Comment by gvanem** [comment]
Check [here](https://github.com/zodiacon/WindowsInternals/blob/master/MemInfo/MemInfo.cpp) for an improved version. Basically `meminfo.cpp` does the same as `pfn.c`.
