### ISSUE TITLE
"Cannot found specified process"

### ISSUE THREAD

**Issue by stdedos** [processhacker/plugins-extra#46]
Coming from: https://github.com/processhacker2/plugins-extra/issues/14#issuecomment-350511711

![image](https://user-images.githubusercontent.com/133706/33805664-3e934d04-ddc5-11e7-809d-4ff1311968f0.png)

Is it that my ProcessHacker is too old? (2.39.124)
I doubt that Windows are "missing" something (10 x64, `%SYSTEM32%/dbghelp.dll` exists)

If so ... could the plugins have versioning or something that prevents them from simply "crashing"?

**Comment by sgeto** [comment]
> Is it that my ProcessHacker is too old? (2.39.124)

Maybe. Have you tried them with newer version of ProcessHacker?

**Comment by stdedos** [comment]
@sgeto Well, since it's not "released" yet, I didn't want to update (because I "heavily depend" on it).

But then I thought, it is so old atm, it's probably not worth it (same reasoning with plugins).
And indeed, that was the issue. Thanks for the nudge
