### ISSUE TITLE
r6187 проблемы с PH SDK - MS VC++14 сообщает о 960 синтаксичеких ошибках 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#5]
После обновления компилятора и устнановки MS SDK 10A при сборке plugins-extra VC++14 сообщает о 960 синтаксичеких ошибках в ./trunk/sdk/include/*.h рабочей копии исходников и не собирает плагины - собрано 0/16. Приложил логи компилятора к сообщению http://wj32.org/processhacker/forums/viewtopic.php?f=8&p=6474#p6473, но пока не знаю как разумнее поступить - может собирать эти плагины в VC++12 (2013)? 

Прошу совета.

**Comment by dmex** [comment]
Fixed.

**Comment by VictorVG** [comment]
Огромное спасибо!
