### ISSUE TITLE
Firewall causes crashes after elevation

### ISSUE THREAD

**Issue by Baddest-Juju** [processhacker/plugins-extra#50]
Windows x64, 3.0.1146 x64, plugins-extra as of commit 48, built x64 Release plugins, put them in the directory, started them all up without a problem.

Everything is fine until I elevate, then the program crashes randomly. I had to hunt down which one was the causes and it turned out to be the Firewall.

Hope you get it fixed because it's the most useful one. (Well, aside from Terminator, but, yano, Steam.)

**Comment by dmex** [comment]
> plugins-extra as of commit 48

Github uses hashes, what commit is 48? 

> Everything is fine until I elevate, then the program crashes randomly

I've pushed some fixes for Norton Security... Can you build the latest version and see if it still happens?

**Comment by Baddest-Juju** [comment]
Apologies, I meant Merge Request #48 

I don't use Norton so I don't see why that would make a difference. Guess I could try though..

**Comment by Baddest-Juju** [comment]
Seems to be working now, thanks.

**Comment by Baddest-Juju** [comment]
Oh and for the record I use ESET NOD32 Antivirus.
