### ISSUE TITLE
[Request] Option to replace svchost.exe Description with services associated

### ISSUE THREAD

**Issue by Baddest-Juju** [processhacker/plugins-extra#51]
Currently all svchost processes say Host Process for Windows Services in Description. I understand it's supposed to be that and it's not something you set there, but I think it could be changed just for this process to be more helpful since there are so very many now.

I'd like an option to have the services that are listed in the tooltip be there instead (the longnames in parentheses preferably), separated by semi-colons if there's more than one, sorted alphabetically.

Also, a 'Service Count' column too, in much the same way there's a subprocess count.

**Comment by dmex** [comment]
> I'd like an option to have the services that are listed in the tooltip be there instead

Process Hacker already does this 👍 
https://i.imgur.com/T5zvmsT.png

> Also, a 'Service Count' column too, in much the same way there's a subprocess count.

You posted this on the wrong issue tracker. The issue tracker for Process Hacker is here:
https://github.com/processhacker2/processhacker/issues

**Comment by Baddest-Juju** [comment]
You misunderstood what I was saying. I'm aware of Services being in the tooltip. I wanted a plugin that would make that same information be available in the Column, under the Description category, replacing the 'Host Process For Windows Services' designator.

I posted in this issue tracker intentionally. I posted it here because It was simply my guess that it would first be a non-core plugin.

**Comment by dmex** [comment]
> You misunderstood what I was saying.

 😄 

> I wanted a plugin that would make that same information be available in the Column, under the Description category, replacing the 'Host Process For Windows Services' designator.

What you're asking for is a Name column exactly like the one used by Task Manager.  The description column is for the file description and users would expect that to remain the case.

**Comment by Baddest-Juju** [comment]
I know of no way to do that in Task Manager. I've looked through the Select Column menu and I see no such option.

I think having it replace its default Description would be the most helpful just for saving on horizontal space.

**Comment by Baddest-Juju** [comment]
Oh wait, you meant the Processes tab, where if you scroll down you'll see Process Host for a lot of things?

Sort of. I'd really like the service names tied directly to the processes though, even if there is more than one service name for a specific process sometimes. (There could be an option to split them up into duplicates with one service name a piece maybe...)

**Comment by dmex** [comment]
Dup of above issue 406
