### ISSUE TITLE
Debug View wierdness

### ISSUE THREAD

**Issue by tigros** [processhacker/plugins-extra#53]
I haven't spent much time on this yet but why does the 64 bit debug version of dbgview work while the release version doesn't? the release version just stays blank. maybe its me.

**Comment by tigros** [comment]
it's interesting that turning off compiler optimization makes it work. The global one works tho with optimization. Maybe you've got a compiler bug spotted?

**Comment by gvanem** [comment]
I might add that selecting *Save*  to file, the list-view gets written to file in reverse order.  

I'm not so much into ComCtl32 and ListViews, but AFAICS in `dialog.c` and `DbgGetStringForSelectedLogEntries()`, the entries in `Context->LogMessageList->Items[]` are ordered on insertion-time. Hence with this patch, it works better:
```diff
--- a/plugins-extra/DbgViewPlugin/dialog.c 2018-03-26 21:59:42
+++ b/plugins-extra/DbgViewPlugin/dialog.c 2018-03-27 17:02:17
@@ -68,7 +68,7 @@

     PhInitializeStringBuilder(&stringBuilder, 0x100);

-    i = Context->ListViewCount - 1;
+    i = 0;

     while (TRUE)
     {
@@ -107,10 +107,10 @@

 ContinueLoop:

-        if (i == 0)
+        if (i >= Context->ListViewCount - 1)
             break;

-        i--;
+        i++;
     }

     return PhFinalStringBuilderString(&stringBuilder);
```
