### ISSUE TITLE
Firewall Monitor Plugin doesn't work on Win 10 v1809

### ISSUE THREAD

**Issue by skipik** [processhacker/plugins-extra#66]
It doesn't show any entries at all on the new Windows 10 v1809 x64, just white background when I click to the Firewall tab in PH. Could you investigate the problem please?

**Comment by gvanem** [comment]
Can I ask a question regarding `FwpUclnt.dll`?

I'm creating my own Firewall Monitor in [Wsock-trace](https://github.com/gvanem/wsock-trace).
There I see a mysterious value of `0x00003903L` in some `FWPM_NET_EVENT_x::msFwpDirection` members.

According to you code, `FORWARD` is `0x00003902L`. So what is the `0x00003903L` value? 
I found nothing via Google 🤒

**Comment by dmex** [comment]
@gvanem 

You should create new issues for questions like these.
