### ISSUE TITLE
Can't build plugins-extra use new SDK (r6266)

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#7]
Development plugins-extra can't build after update PH SDK up to r6265+. Error log is attached:

[AvgCpuPlugin.txt](https://github.com/dmex/plugins-extra/files/64881/AvgCpuPlugin.txt)
[AvgCpuPlugin.txt](https://github.com/dmex/plugins-extra/files/64882/AvgCpuPlugin.txt)
[BootEntriesPlugin.txt](https://github.com/dmex/plugins-extra/files/64884/BootEntriesPlugin.txt)
[DbgViewPlugin.txt](https://github.com/dmex/plugins-extra/files/64887/DbgViewPlugin.txt)
[DiskDrivesPlugin.txt](https://github.com/dmex/plugins-extra/files/64886/DiskDrivesPlugin.txt)
[DnsCachePlugin.txt](https://github.com/dmex/plugins-extra/files/64885/DnsCachePlugin.txt)
[FirewallMonitorPlugin.txt](https://github.com/dmex/plugins-extra/files/64883/FirewallMonitorPlugin.txt)
[HexPidPlugin.txt](https://github.com/dmex/plugins-extra/files/64891/HexPidPlugin.txt)
[NetExtrasPlugin.txt](https://github.com/dmex/plugins-extra/files/64892/NetExtrasPlugin.txt)
[NvGpuPlugin.txt](https://github.com/dmex/plugins-extra/files/64890/NvGpuPlugin.txt)
[PerfMonPlugin.txt](https://github.com/dmex/plugins-extra/files/64889/PerfMonPlugin.txt)
[ROTViewerPlugin.txt](https://github.com/dmex/plugins-extra/files/64888/ROTViewerPlugin.txt)
[SecurityExplorer.txt](https://github.com/dmex/plugins-extra/files/64893/SecurityExplorer.txt)
[ServiceBackupRestorePlugin.txt](https://github.com/dmex/plugins-extra/files/64896/ServiceBackupRestorePlugin.txt)
[SetCriticalPlugin.txt](https://github.com/dmex/plugins-extra/files/64894/SetCriticalPlugin.txt)
[TaskbarExtPlugin.txt](https://github.com/dmex/plugins-extra/files/64897/TaskbarExtPlugin.txt)
[WaitChainPlugin.txt](https://github.com/dmex/plugins-extra/files/64895/WaitChainPlugin.txt)

On new PH SDK is removing definition for structure _PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY_ in to file ./include/ntpsapi.h (strings 542 - 556):

```
// private
typedef struct _PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY
{
union
{
ULONG Flags;
struct
{
ULONG EnableControlFlowGuard: 1;
ULONG ReservedFlags: 31;
};
};
} PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY, * PPROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY;

// private
```

then code used this structure can't work...

**Comment by dmex** [comment]
You need to update the Plugins SDK...

1. Build ProcessHacker in Release mode for both 32bit and 64bit.
1. Run "\Process Hacker\2.x\trunk\build\sdk\makesdkwithdoc.cmd"

**Comment by VictorVG** [comment]
Thank you very much! The order in armor. Close as spent.
