### ISSUE TITLE
fw.c Win8 binary version

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/plugins-extra#70]
Its the same as Win 8.1 i.e. 0x0214

        public enum FW_BINARY_VERSION: ushort
        {
            FW_BINARY_VERSION_VISTA     = 0x0200,
            FW_BINARY_VERSION_SERVER2K8 = 0x0201,
            FW_BINARY_VERSION_SEVEN     = 0x020A,
            FW_BINARY_VERSION_WIN8      = 0x0214,

            FW_BINARY_VERSION_WIN10     = 0x0216,
            FW_BINARY_VERSION_THRESHOLD = 0x0218, // 1507
            FW_BINARY_VERSION_THRESHOLD2= 0x0219, // 1511
            FW_BINARY_VERSION_REDSTONE1 = 0x021A, // 1607
            FW_BINARY_VERSION_170x      = 0x021B, // Redstone 2 & Redstone 3
            FW_BINARY_VERSION_180x      = 0x021C, // Redstone 4 & Redstone 5
            FW_BINARY_VERSION_19Hx      = 0x021E
        }

**Comment by DavidXanatos** [comment]
that may also be of use:
comments denote since which windows version what fields were added

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public struct FW_RULE
        {
            public IntPtr pNext;

            public ushort wSchemaVersion;
            public string wszRuleId;
            public string Name;
            public string Description;
            public FW_PROFILE_TYPE Profiles;
            public FW_DIRECTION Direction;
            public IpProtocol IpProtocol;
            public FW_PROTOCOL_UNION protocolUnion;
            public FW_ADDRESSES LocalAddresses;
            public FW_ADDRESSES RemoteAddresses;
            public FW_INTERFACE_LUIDS LocalInterfaceIds;
            public FW_INTERFACE_TYPE LocalInterfaceTypes;
            public string LocalApplication;
            public string LocalService;
            public FW_ACTION Action;
            public FW_RULE_FLAGS wFlags;
            public string RemoteMachineAuthorizationList;
            public string RemoteUserAuthorizationList;
            public string EmbeddedContext;
            public FW_OS_PLATFORM_LIST PlatformValidity;
            public FW_RULE_STATUS Status;
            public FW_RULE_ORIGIN_TYPE Origin;
            public string GPOName;
            public uint Reserved;
            // up to here its windows 7 comatible

            // in 8 & 8.1
            public IntPtr pMetaData;
            public string LocalUserAuthorizationList;
            public string PackageId;
            public string LocalUserOwner;
            public FW_TRUST_TUPLE_KEYWORD dwTrustTupleKeywords;

            // since 1507
            public FW_NETWORK_NAMES OnNetworkNames;
            public string SecurityRealmId;

            // since 1511
            public FW_RULE_FLAGS2 wFlags2;

            // since 1607
            public FW_NETWORK_NAMES RemoteOutServerNames;

            // since 1703
            public string Fqbn;
            public uint compartmentId;
        }

**Comment by dmex** [comment]
> Its the same as Win 8.1 i.e. 0x0214

The value is correct. You can check AuthFWSnapin.dll
