### ISSUE TITLE
Pontential bug with DPI Awareness plugin

### ISSUE THREAD

**Issue by kristibektashi** [processhacker/plugins-extra#77]
DPI awareness plugin fails to build
My host is Windows 10 x64 (version 20h2)
I am using Visual Studio Community 2019
Here is the output from Visual Studio:
[DPIAwarenessBuildLog.txt](https://github.com/processhacker/plugins-extra/files/5469278/DPIAwarenessBuildLog.txt)

**Comment by VictorVG** [comment]
Just is old code. Simple use [**Patch DpiAwarenessExtPlugin and NvGpuPlugin for support Process Hacker Git c2d9325**](https://github.com/processhacker/plugins-extra/issues/76) and build success. I fix it 4 days ago.:)

**Comment by dmex** [comment]
Dup of #76
