### ISSUE TITLE
Падение PH при запросе детальной информации о видеокарте

### ISSUE THREAD

**Issue by z0hm** [processhacker/plugins-extra#8]
WinXPSP2, GF7600GT, PH2.37.6283, NvGpuPlugin 1.1.0.0. 

System Information - LMB GF7600GT - Details = процесс PH испаряется бесследно.
Если VC не поддерживается, то надо либо выдавать соответствующее сообщение, либо не отображать кнопку Details, а не падать.

Также, ширина полей Clocks, Fan, Temperature, Voltage не масштабируется, является чрезмерной, и может быть уменьшена в общей сложности на 180-200px. Поля отображаются без изъянов при ширине окна в 730px, при меньшей ширине окна, правый край поля Voltage уходит за край окна.

**Comment by z0hm** [comment]
NvGpuPlugin 1.1.0.0. Если VC не поддерживается, то надо выдавать соответствующее сообщение, либо не отображать кнопку Details, а не падать.

**Comment by VictorVG** [comment]
This GPU chip - NVIDIA G73 is were old.:) On GF116/GK107 plug-in work w/o problem's:

![gk107](https://cloud.githubusercontent.com/assets/906886/12003278/0fb5813a-ab29-11e5-9186-4bb8eb83cef5.png)
