### ISSUE TITLE
[Question] Terminator usage

### ISSUE THREAD

**Issue by vault101** [processhacker/plugins-extra#96]
After build of main repo and TerminatorPlugin, now I have processhacker\bin\Debug64\plugins\TerminatorPlugin.dll and processhacker\bin\Debug64\ProcessHacker.exe. But after launching ProcessHacker.exe can't see Terminator in plugin list. How to enable it and how to use it?

**Comment by dmex** [comment]
`EnableSafeDefaultPlugins`
